sonar.projectKey=motormetrics_motormetrics
sonar.organization=motormetrics
sonar.projectName=motormetrics

sonar.sources=apps,packages
sonar.exclusions=**/node_modules/**,**/dist/**,**/.next/**,**/coverage/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.tests=apps,packages
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.javascript.lcov.reportPaths=**/coverage/lcov.info
