name: Lockfile Integrity

on:
  pull_request:
    paths:
      - pnpm-lock.yaml

env:
  HEROUI_AUTH_TOKEN: ${{ secrets.HEROUI_AUTH_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lockfile-integrity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Check for lockfile tampering
        uses: tartinerlabs/lockfile-integrity@595c3f499363a060840aa387d8eaae781e73b135 # v1.2.0
        with:
          base-ref: ${{ github.base_ref }}
